FinalProject/News/News/urls.py
from django.contrib import admin
from django.urls import path
from post.views import post_list
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', post_list),
    path('posts/', include('post.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

FinalProject/News/post/urls.py
from django.urls import path, include
from post.views import *
from django.conf.urls import url
from post import views as core_views

app_name = 'post'
urlpatterns = [
    path('', post_list, name='post_list'),
    path('create/', post_create, name='create'),
    path('delete/<int:id>/', post_delete, name='delete'),
    path('detail/<int:id>/', post_detail, name='detail'),
    path('update/<int:id>/', post_update, name='update'),
    url(r'^signup/$', core_views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

]




















FinalProject/News/post/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


def upload_location(instance, filename):

    return f'{instance.id}, {filename}'


class Post(models.Model):
    title = models.CharField(max_length=70)
    title_class = models.CharField(max_length=50, default='Any')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             default=1,
                             on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              height_field='height_field',
                              width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()

    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return f'/posts/detail/{self.id}'

    def __str__(self):
        return self.title


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)


FinalProject/News/post/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from post.models import Post


class Form(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image'
        ]


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

FinalProject/News/post/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils import timezone
from post.models import Post
from post.forms import Form, SignUpForm
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def home_page(request):
    return HttpResponse('<h1> Home </h1>')


def post_list(request):
    queryset = Post.objects.order_by('-id')
    paginator = Paginator(queryset, 6)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {
        'title': 'Post list',
        'object_list': queryset,
        'page_request_var': page_request_var
    }
    return render(request, 'post_list.html', context)


def post_create(request):

    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = Form(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'Post created!!!')
         

    context = {
        'title': 'Post create',
        'form': form
    }
    return render(request, 'create.html', context)


def post_update(request, id):

    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, id=id)
    form = Form(request.POST or None, request.FILES or None, instance=instance)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href = '#'>Post created!!!</a> ", extra_tags='safe_html')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title': 'Post update',
        'form': form
    }
    return render(request, 'create.html', context)


def post_delete(request, id):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, id=id)
    instance.delete()
    return redirect('post:post_list')


def post_detail(request, id):
    instance = get_object_or_404(Post, id=id)
    context = {
        'title': 'Post detail',
        'object': instance
    }
    return render(request, 'detail.html', context)




def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('post:post_list')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})








FinalProject/News/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}NEWS{% endblock head_title %}</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <style>{% block style %}{% endblock style %}</style>
</head>
<body>


    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom ">
      <a href="{% url 'post:post_list' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">

        <span class="fs-4">U-News</span>
      </a>

      <ul class="nav nav-pills" >

        {% if not request.user.is_staff or not request.user.is_superuser %}
          <li class="nav-item"><a href="{% url 'post:signup' %}" class="nav-link">Sign In</a></li>
        <li class="nav-item"><a href="{% url 'post:login' %}" class="nav-link">Log in</a></li>
          {% else %}
        <li class="nav-item"><a href="{% url 'post:create' %}" class="nav-link">Create</a></li>
        <li class="nav-item"><a href="{% url 'post:logout' %}" class="nav-link">Log out</a></li>
          {% endif %}
      </ul>
    </header>

    {% include 'message.html' %}

    <div class="container">
        {% block content %}{% endblock content %}
    </div>



  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Instagram</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">GitHub</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Whatsapp</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Twitter</a></li>

    </ul>
    <p class="text-center text-muted">© 2022 Logos IT</p>
  </footer>






    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>




















FinalProject/News/templates/create.html
{% extends 'base.html' %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" class="btn btn-primary" value="Create post!">
        </form>
    </div>



{% endblock content %}

FinalProject/News/templates/detail.html
{% extends 'base.html' %}

{% block head_title %}{{ object.title }}{% endblock head_title %}

{% block content %}
    <div class="detail_info">
        <h1 class="display-4 ">{{ object.title }}</h1>
            {% if object.image %}
                <figure class="figure">
                    <img src="{{ object.image.url }}" class="figure-img img-fluid rounded" alt=" ">
                </figure>
            {% endif %}
        <div class="content">
            <p>{{ object.content|linebreaks }}</p>
            <div class="info">
                {% if object.user.get_full_name %}
                    <p>Author: {{ object.user.get_full_name }}</p>
                {% endif %}
                <small>{{ object.timestamp }}</small>
            </div>
       </div>
    <h2>Comments</h2>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
            <p class="card-text">
                {% if not post.comments.all %}
                    No Comments Yet <a href="#">
                    Add One</a>
                {% else %}
                    {% for comment in post.comments.all %}
                        <strong>
                        {{ comment.name }} -
                        {{ comment.date_added }}
                        </strong>
                        {{ comment.body }}
                    {% endfor %}
                {% endif %}
                </p>
            </div>
        </div>

    </div>
{% endblock %}

FinalProject/News/templates/message.html

    {% if messages %}
         <div class="messages">
                <ul class="messages">
                   {% for message in messages %}
                       <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if 'safe_html' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
                   {% endfor %}
                </ul>
         </div>
        {% endif %}

FinalProject/News/templates/post_list.html
{% extends 'base.html'%}
{% block content %}
{% for object in object_list %}
    {% if object.image %}

    <div class="album py-3 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3l">
                <div class="card" style="width: 24rem;">
                        <img src="{{ object.image.url }}" class="card-img-top" alt=" ">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                        <a href="{{ object.get_absolute_url }}" class="btn btn-primary">Continue reading...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endif %}
    {% endfor %}





        <div class="paginator">
            <span class="step-link">
                {% if object_list.has_previous %}
                    <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}">Previous</a>
                {% endif %}
            <span class="current">
                {{ object_list.number }} of {{ object_list.paginator.num_pages }}
            </span>
                {% if object_list.has_next %}
                    <a href="?{{ page_request_var }}={{ object_list.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
    </div>















{% endblock content %}





